// <auto-generated />
namespace W2022A6NNB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class trackaudio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(trackaudio));
        
        string IMigrationMetadata.Id
        {
            get { return "202204210019339_track-audio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
